# Generated by Django 2.0.5 on 2019-11-24 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('brief', models.CharField(blank=True, max_length=256, null=True)),
                ('max_menbers', models.IntegerField(default=200)),
            ],
            options={
                'verbose_name_plural': '聊天组',
                'verbose_name': '聊天组',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='昵称')),
                ('signature', models.CharField(blank=True, max_length=256, null=True, verbose_name='签名')),
                ('avator', models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='头像')),
                ('friends', models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='chat.UserProfile')),
                ('user', models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'verbose_name': '用户表',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='group_admins', to='chat.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='menbers',
            field=models.ManyToManyField(blank=True, related_name='group_members', to='chat.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=True, to='chat.UserProfile'),
        ),
    ]
